### ISSUE TITLE
Invalid colorName

### ISSUE THREAD

**Issue by s0600204** [Figure53/QLabKit.objc#21]
Hi, I wish to make the following observation:

On line 42 of `lib/QLKColor.m`, `"lightblue"` is given as a valid colour.

However, the `lightblueColor` class/object/thing [^1] was removed in 1a7bce3.

Thus, there is a good chance that if a cue has a `colorName` of `"lightblue"` (possible with QLab prior to version 4.5 [^2]), then something untoward may happen.

----

^1 - I'm not familiar with Objective-C, so I'm not sure of the appropriate terminology here.
^2 - From QLab 4.5 onward, QLab ignores attempts (via OSC or AppleScript) to set a cue's `colorName` to a named colour it doesn't recognise.

**Comment by balord** [comment]
Thanks @s0600204 for pointing this out. It should be fixed now!
